#
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'elastic_search_thrift/mini_thrift'
require 'elastic_search_thrift/elasticsearch_types'

module ElasticSearchThrift
end
